# Generated by Django 5.1.3 on 2024-11-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UGResponsavel',
            fields=[
                ('codigo', models.CharField(db_column='codigoUGResponsavel', max_length=15, primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='nomeUGResponsavel', max_length=150)),
            ],
            options={
                'db_table': 'UGResponsavel',
                'managed': True,
            },
        ),
    ]
