# Generated by Django 5.1.3 on 2024-11-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execucaoorcamentariadetalhada', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoDespesa',
            fields=[
                ('codigo', models.CharField(db_column='codigoGrupoDespesa', max_length=15, primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='nomeGrupoDespesa', max_length=150)),
            ],
            options={
                'db_table': 'GrupoDespesa',
                'managed': True,
            },
        ),
    ]
