# Generated by Django 5.1.3 on 2024-11-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execucaoorcamentariadetalhada', '0002_grupodespesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaAgregada',
            fields=[
                ('codigo', models.CharField(db_column='codigoDespesaAgregada', max_length=15, primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='nomeDespesaAgregada', max_length=150)),
            ],
            options={
                'db_table': 'DespesaAgregada',
                'managed': True,
            },
        ),
    ]
