# Generated by Django 5.1.3 on 2024-11-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execucaoorcamentariadetalhada', '0003_despesaagregada'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoGoverno',
            fields=[
                ('codigo', models.CharField(db_column='codigoAcaoGoverno', max_length=15, primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='nomeAcaoGoverno', max_length=150)),
            ],
            options={
                'db_table': 'AcaoGoverno',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EtapaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='nomeEtapaCredito', max_length=150)),
            ],
            options={
                'db_table': 'EtapaCredito',
                'managed': True,
            },
        ),
    ]
