# Generated by Django 5.1.3 on 2024-11-16 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execucaoorcamentariadetalhada', '0005_naturezadespesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoDetalhada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(db_column='saldo', decimal_places=2, max_digits=10)),
                ('acaoGoverno', models.ForeignKey(db_column='codigoAcaoGoverno', on_delete=django.db.models.deletion.PROTECT, to='execucaoorcamentariadetalhada.acaogoverno')),
                ('despesaAgregada', models.ForeignKey(db_column='codigoDespesaAgregada', on_delete=django.db.models.deletion.PROTECT, to='execucaoorcamentariadetalhada.despesaagregada')),
                ('etapaCredito', models.ForeignKey(db_column='idEtapaCredito', on_delete=django.db.models.deletion.PROTECT, to='execucaoorcamentariadetalhada.etapacredito')),
                ('grupoDespesa', models.ForeignKey(db_column='codigoGupooDespesa', on_delete=django.db.models.deletion.PROTECT, to='execucaoorcamentariadetalhada.grupodespesa')),
                ('naturezaDespesa', models.ForeignKey(db_column='codigoNaturezaDespesa', on_delete=django.db.models.deletion.PROTECT, to='execucaoorcamentariadetalhada.naturezadespesa')),
                ('ugResponsavel', models.ForeignKey(db_column='codigoUGResponsavel', on_delete=django.db.models.deletion.PROTECT, to='execucaoorcamentariadetalhada.ugresponsavel')),
            ],
        ),
    ]
